[package]
authors = ["saruyoshida"]
name = "cavityflow3d"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
ndarray = { version = "0.16.1", default-features = false}









